services:
  - node:13

stages:
  - test

before_script:
  - yarn config set registry https://registry.npm.taobao.org
  - yarn install
job1:
  stage: test
  tags:
    - node-runner
  script:
    # - npm run test
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish

